"""add loyalty tiers, sale override audit, whatsapp/ai logs, role hierarchy update

Revision ID: 69d564ea37da
Revises: aefa08ab31c8
Create Date: 2026-07-10 00:58:52.504285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69d564ea37da'
down_revision = 'aefa08ab31c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_chat_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('intent', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_chat_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_chat_logs_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_chat_logs_created_at'), ['created_at'], unique=False)

    op.create_table('whatsapp_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('to_number', sa.String(length=20), nullable=False),
    sa.Column('message_type', sa.Enum('invoice', 'payment_reminder', 'prescription_reminder', 'refill_reminder', 'promotional'), nullable=False),
    sa.Column('reference_type', sa.String(length=20), nullable=True),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('message_body', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('queued', 'sent', 'failed'), nullable=True),
    sa.Column('error_message', sa.String(length=255), nullable=True),
    sa.Column('sent_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sent_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('whatsapp_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_whatsapp_logs_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_whatsapp_logs_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('loyalty_programs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('silver_min_spend', sa.Numeric(precision=12, scale=2), nullable=True))
        batch_op.add_column(sa.Column('gold_min_spend', sa.Numeric(precision=12, scale=2), nullable=True))
        batch_op.add_column(sa.Column('platinum_min_spend', sa.Numeric(precision=12, scale=2), nullable=True))
        batch_op.add_column(sa.Column('silver_cashback_pct', sa.Numeric(precision=5, scale=2), nullable=True))
        batch_op.add_column(sa.Column('gold_cashback_pct', sa.Numeric(precision=5, scale=2), nullable=True))
        batch_op.add_column(sa.Column('platinum_cashback_pct', sa.Numeric(precision=5, scale=2), nullable=True))
        batch_op.add_column(sa.Column('referral_bonus_points', sa.Integer(), nullable=True))

    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('loyalty_tier', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('referred_by_patient_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'patients', ['referred_by_patient_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('interaction_override_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('interaction_override_reason', sa.String(length=255), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['interaction_override_by'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('interaction_override_reason')
        batch_op.drop_column('interaction_override_by')

    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('referred_by_patient_id')
        batch_op.drop_column('loyalty_tier')

    with op.batch_alter_table('loyalty_programs', schema=None) as batch_op:
        batch_op.drop_column('referral_bonus_points')
        batch_op.drop_column('platinum_cashback_pct')
        batch_op.drop_column('gold_cashback_pct')
        batch_op.drop_column('silver_cashback_pct')
        batch_op.drop_column('platinum_min_spend')
        batch_op.drop_column('gold_min_spend')
        batch_op.drop_column('silver_min_spend')

    with op.batch_alter_table('whatsapp_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_whatsapp_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_whatsapp_logs_business_id'))

    op.drop_table('whatsapp_logs')
    with op.batch_alter_table('ai_chat_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_chat_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_ai_chat_logs_business_id'))

    op.drop_table('ai_chat_logs')
    # ### end Alembic commands ###
