"""Initial tables

Revision ID: aefa08ab31c8
Revises: 
Create Date: 2026-06-24 02:46:27.488557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aefa08ab31c8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('businesses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('legal_name', sa.String(length=200), nullable=True),
    sa.Column('short_name', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=15), nullable=True),
    sa.Column('alt_phone', sa.String(length=15), nullable=True),
    sa.Column('website', sa.String(length=200), nullable=True),
    sa.Column('address_line1', sa.String(length=200), nullable=True),
    sa.Column('address_line2', sa.String(length=200), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('pincode', sa.String(length=10), nullable=True),
    sa.Column('country', sa.String(length=50), nullable=True),
    sa.Column('gstin', sa.String(length=15), nullable=True),
    sa.Column('pan', sa.String(length=10), nullable=True),
    sa.Column('drug_license_no', sa.String(length=50), nullable=True),
    sa.Column('drug_license_no2', sa.String(length=50), nullable=True),
    sa.Column('fssai_no', sa.String(length=20), nullable=True),
    sa.Column('bank_name', sa.String(length=100), nullable=True),
    sa.Column('bank_branch', sa.String(length=100), nullable=True),
    sa.Column('bank_account_no', sa.String(length=20), nullable=True),
    sa.Column('bank_ifsc', sa.String(length=11), nullable=True),
    sa.Column('upi_id', sa.String(length=50), nullable=True),
    sa.Column('logo_filename', sa.String(length=200), nullable=True),
    sa.Column('signature_filename', sa.String(length=200), nullable=True),
    sa.Column('tagline', sa.String(length=200), nullable=True),
    sa.Column('currency', sa.String(length=5), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('date_format', sa.String(length=20), nullable=True),
    sa.Column('financial_year_start', sa.Integer(), nullable=True),
    sa.Column('is_gst_registered', sa.Boolean(), nullable=True),
    sa.Column('default_gst_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('default_supply_type', sa.String(length=10), nullable=True),
    sa.Column('invoice_prefix', sa.String(length=10), nullable=True),
    sa.Column('po_prefix', sa.String(length=10), nullable=True),
    sa.Column('gr_prefix', sa.String(length=10), nullable=True),
    sa.Column('return_prefix', sa.String(length=10), nullable=True),
    sa.Column('invoice_terms', sa.Text(), nullable=True),
    sa.Column('invoice_footer', sa.Text(), nullable=True),
    sa.Column('enable_loyalty', sa.Boolean(), nullable=True),
    sa.Column('enable_whatsapp', sa.Boolean(), nullable=True),
    sa.Column('enable_abha', sa.Boolean(), nullable=True),
    sa.Column('enable_eprescription', sa.Boolean(), nullable=True),
    sa.Column('enable_barcode', sa.Boolean(), nullable=True),
    sa.Column('enable_sms', sa.Boolean(), nullable=True),
    sa.Column('setup_complete', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gstin')
    )
    op.create_table('drug_interactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('drug_a_generic', sa.String(length=150), nullable=False),
    sa.Column('drug_b_generic', sa.String(length=150), nullable=False),
    sa.Column('severity', sa.Enum('minor', 'moderate', 'major', 'contraindicated'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('drug_interactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_drug_interactions_drug_a_generic'), ['drug_a_generic'], unique=False)
        batch_op.create_index(batch_op.f('ix_drug_interactions_drug_b_generic'), ['drug_b_generic'], unique=False)

    op.create_table('sequences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('current_value', sa.Integer(), nullable=False),
    sa.Column('prefix', sa.String(length=10), nullable=True),
    sa.Column('pad_length', sa.Integer(), nullable=True),
    sa.Column('reset_yearly', sa.Boolean(), nullable=True),
    sa.Column('last_reset_year', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sequences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sequences_key'), ['key'], unique=True)

    op.create_table('branches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('is_headquarters', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('phone', sa.String(length=15), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('address_line1', sa.String(length=200), nullable=True),
    sa.Column('address_line2', sa.String(length=200), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('pincode', sa.String(length=10), nullable=True),
    sa.Column('drug_license_no', sa.String(length=50), nullable=True),
    sa.Column('gstin', sa.String(length=15), nullable=True),
    sa.Column('manager_name', sa.String(length=100), nullable=True),
    sa.Column('manager_phone', sa.String(length=15), nullable=True),
    sa.Column('opening_time', sa.Time(), nullable=True),
    sa.Column('closing_time', sa.Time(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('chart_of_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.Enum('asset', 'liability', 'equity', 'revenue', 'expense'), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['chart_of_accounts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'code', name='uq_account_code')
    )
    with op.batch_alter_table('chart_of_accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chart_of_accounts_business_id'), ['business_id'], unique=False)

    op.create_table('doctors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('doctor_code', sa.String(length=20), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('specialization', sa.String(length=100), nullable=True),
    sa.Column('qualification', sa.String(length=100), nullable=True),
    sa.Column('registration_no', sa.String(length=50), nullable=True),
    sa.Column('phone', sa.String(length=15), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('clinic_name', sa.String(length=150), nullable=True),
    sa.Column('clinic_address', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_doctors_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_doctors_doctor_code'), ['doctor_code'], unique=True)

    op.create_table('loyalty_programs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('points_per_rupee', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('rupees_per_point', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('min_redeem_points', sa.Integer(), nullable=True),
    sa.Column('expiry_days', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id')
    )
    op.create_table('medicine_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['medicine_categories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('medicine_categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_medicine_categories_business_id'), ['business_id'], unique=False)

    op.create_table('patients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('patient_code', sa.String(length=20), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('gender', sa.Enum('male', 'female', 'other'), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('abha_id', sa.String(length=20), nullable=True),
    sa.Column('blood_group', sa.String(length=5), nullable=True),
    sa.Column('allergies', sa.Text(), nullable=True),
    sa.Column('chronic_conditions', sa.Text(), nullable=True),
    sa.Column('loyalty_points', sa.Integer(), nullable=True),
    sa.Column('total_purchases', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_patients_abha_id'), ['abha_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_patients_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_patients_patient_code'), ['patient_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_patients_phone'), ['phone'], unique=False)

    op.create_table('suppliers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('supplier_code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('contact_person', sa.String(length=150), nullable=True),
    sa.Column('phone', sa.String(length=15), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('gst_number', sa.String(length=15), nullable=True),
    sa.Column('drug_license_no', sa.String(length=50), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('payment_terms', sa.Integer(), nullable=True),
    sa.Column('credit_limit', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('outstanding', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('performance_score', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_suppliers_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_suppliers_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_suppliers_supplier_code'), ['supplier_code'], unique=True)

    op.create_table('gst_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.Enum('sale', 'purchase', 'sale_return', 'purchase_return'), nullable=False),
    sa.Column('reference_id', sa.Integer(), nullable=False),
    sa.Column('reference_type', sa.String(length=20), nullable=True),
    sa.Column('gstin', sa.String(length=15), nullable=True),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('taxable_value', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('cgst_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('cgst_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('sgst_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('sgst_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('igst_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('igst_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('hsn_code', sa.String(length=8), nullable=True),
    sa.Column('fy', sa.String(length=9), nullable=True),
    sa.Column('period', sa.String(length=7), nullable=True),
    sa.Column('filed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('gst_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gst_transactions_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_gst_transactions_fy'), ['fy'], unique=False)
        batch_op.create_index(batch_op.f('ix_gst_transactions_period'), ['period'], unique=False)
        batch_op.create_index(batch_op.f('ix_gst_transactions_transaction_date'), ['transaction_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_gst_transactions_transaction_type'), ['transaction_type'], unique=False)

    op.create_table('medicines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('medicine_code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('generic_name', sa.String(length=200), nullable=True),
    sa.Column('brand_name', sa.String(length=200), nullable=True),
    sa.Column('salt_composition', sa.Text(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('manufacturer', sa.String(length=200), nullable=True),
    sa.Column('hsn_code', sa.String(length=20), nullable=True),
    sa.Column('schedule_type', sa.String(length=5), nullable=False),
    sa.Column('gst_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('mrp', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('purchase_rate', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('selling_rate', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('pack_size', sa.Integer(), nullable=True),
    sa.Column('barcode', sa.String(length=50), nullable=True),
    sa.Column('qr_data', sa.Text(), nullable=True),
    sa.Column('rack_location', sa.String(length=50), nullable=True),
    sa.Column('storage_condition', sa.String(length=20), nullable=True),
    sa.Column('prescription_req', sa.Boolean(), nullable=True),
    sa.Column('temp_sensitive', sa.Boolean(), nullable=True),
    sa.Column('narcotic_flag', sa.Boolean(), nullable=True),
    sa.Column('returnable_flag', sa.Boolean(), nullable=True),
    sa.Column('reorder_level', sa.Integer(), nullable=True),
    sa.Column('max_stock_level', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['category_id'], ['medicine_categories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('medicines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_medicines_barcode'), ['barcode'], unique=True)
        batch_op.create_index(batch_op.f('ix_medicines_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_medicines_generic_name'), ['generic_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_medicines_medicine_code'), ['medicine_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_medicines_name'), ['name'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=True),
    sa.Column('avatar_filename', sa.String(length=200), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('totp_secret', sa.String(length=32), nullable=True),
    sa.Column('totp_enabled', sa.Boolean(), nullable=True),
    sa.Column('failed_login_count', sa.Integer(), nullable=True),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.Column('reset_token', sa.String(length=200), nullable=True),
    sa.Column('reset_token_expiry', sa.DateTime(), nullable=True),
    sa.Column('email_verify_token', sa.String(length=200), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('last_login_ip', sa.String(length=45), nullable=True),
    sa.Column('last_active_at', sa.DateTime(), nullable=True),
    sa.Column('designation', sa.String(length=100), nullable=True),
    sa.Column('qualification', sa.String(length=200), nullable=True),
    sa.Column('drug_license_no', sa.String(length=50), nullable=True),
    sa.Column('registration_no', sa.String(length=50), nullable=True),
    sa.Column('theme', sa.String(length=20), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reset_token')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('module', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('record_type', sa.String(length=50), nullable=True),
    sa.Column('record_id', sa.Integer(), nullable=True),
    sa.Column('old_values', sa.JSON(), nullable=True),
    sa.Column('new_values', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=300), nullable=True),
    sa.Column('endpoint', sa.String(length=200), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_module'), ['module'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_user_id'), ['user_id'], unique=False)

    op.create_table('journal_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('entry_number', sa.String(length=25), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('reference_type', sa.String(length=20), nullable=True),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('narration', sa.Text(), nullable=True),
    sa.Column('total_debit', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total_credit', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entry_number')
    )
    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_journal_entries_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_journal_entries_entry_date'), ['entry_date'], unique=False)

    op.create_table('medicine_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('medicine_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('batch_number', sa.String(length=50), nullable=False),
    sa.Column('mfg_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('reserved_qty', sa.Integer(), nullable=False),
    sa.Column('purchase_rate', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('mrp', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('selling_rate', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('rack_location', sa.String(length=50), nullable=True),
    sa.Column('purchase_item_id', sa.Integer(), nullable=True),
    sa.Column('is_expired', sa.Boolean(), nullable=False),
    sa.Column('is_damaged', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['medicine_id'], ['medicines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('medicine_batches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_medicine_batches_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_medicine_batches_medicine_id'), ['medicine_id'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.Enum('expiry', 'reorder', 'low_stock', 'dead_stock', 'payment_due', 'license_expiry', 'system', 'whatsapp'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('reference_type', sa.String(length=20), nullable=True),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('priority', sa.Enum('low', 'medium', 'high', 'critical'), nullable=True),
    sa.Column('sent_via', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_is_read'), ['is_read'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)

    op.create_table('prescriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('prescription_code', sa.String(length=25), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=True),
    sa.Column('rx_date', sa.Date(), nullable=False),
    sa.Column('image_path', sa.String(length=300), nullable=True),
    sa.Column('eprescription_xml', sa.Text(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('verified_by', sa.Integer(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('validity_days', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'verified', 'dispensed', 'expired'), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('prescriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prescriptions_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_prescriptions_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_prescriptions_prescription_code'), ['prescription_code'], unique=True)

    op.create_table('purchase_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('po_number', sa.String(length=30), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('order_date', sa.Date(), nullable=False),
    sa.Column('expected_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchase_orders_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_orders_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_orders_po_number'), ['po_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_purchase_orders_supplier_id'), ['supplier_id'], unique=False)

    op.create_table('stock_adjustments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('adj_number', sa.String(length=30), nullable=False),
    sa.Column('adj_type', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('adjusted_by', sa.Integer(), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['adjusted_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('adj_number')
    )
    with op.batch_alter_table('stock_adjustments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stock_adjustments_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_adjustments_business_id'), ['business_id'], unique=False)

    op.create_table('journal_entry_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('debit', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('credit', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['chart_of_accounts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['entry_id'], ['journal_entries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('journal_entry_lines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_journal_entry_lines_entry_id'), ['entry_id'], unique=False)

    op.create_table('prescription_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prescription_id', sa.Integer(), nullable=False),
    sa.Column('medicine_id', sa.Integer(), nullable=True),
    sa.Column('generic_name', sa.String(length=150), nullable=True),
    sa.Column('dosage', sa.String(length=100), nullable=True),
    sa.Column('duration', sa.String(length=50), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('dispensed_qty', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['medicine_id'], ['medicines.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['prescription_id'], ['prescriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('prescription_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prescription_items_prescription_id'), ['prescription_id'], unique=False)

    op.create_table('purchase_order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('po_id', sa.Integer(), nullable=False),
    sa.Column('medicine_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('rate', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['medicine_id'], ['medicines.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['po_id'], ['purchase_orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('purchase_order_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchase_order_items_po_id'), ['po_id'], unique=False)

    op.create_table('purchases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('bill_number', sa.String(length=30), nullable=False),
    sa.Column('po_id', sa.Integer(), nullable=True),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('bill_date', sa.Date(), nullable=False),
    sa.Column('invoice_number', sa.String(length=50), nullable=True),
    sa.Column('invoice_date', sa.Date(), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('discount_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('cgst_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('sgst_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('igst_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('paid_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('due_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('payment_mode', sa.String(length=20), nullable=True),
    sa.Column('payment_status', sa.String(length=15), nullable=False),
    sa.Column('ocr_bill_path', sa.String(length=300), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['po_id'], ['purchase_orders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchases_bill_number'), ['bill_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_purchases_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchases_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchases_supplier_id'), ['supplier_id'], unique=False)

    op.create_table('sales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('invoice_number', sa.String(length=25), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('prescription_id', sa.Integer(), nullable=True),
    sa.Column('invoice_date', sa.DateTime(), nullable=False),
    sa.Column('cashier_id', sa.Integer(), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('discount_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('discount_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('cgst_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('sgst_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('igst_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('round_off', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('paid_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('change_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('payment_mode', sa.Enum('cash', 'card', 'upi', 'credit', 'wallet'), nullable=True),
    sa.Column('loyalty_points_used', sa.Integer(), nullable=True),
    sa.Column('loyalty_points_earned', sa.Integer(), nullable=True),
    sa.Column('is_gstin_bill', sa.Boolean(), nullable=True),
    sa.Column('customer_gstin', sa.String(length=15), nullable=True),
    sa.Column('status', sa.Enum('draft', 'confirmed', 'cancelled'), nullable=True),
    sa.Column('is_return', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['cashier_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['prescription_id'], ['prescriptions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sales_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_invoice_date'), ['invoice_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_invoice_number'), ['invoice_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_sales_patient_id'), ['patient_id'], unique=False)

    op.create_table('stock_adjustment_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('adjustment_id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('medicine_id', sa.Integer(), nullable=False),
    sa.Column('qty_before', sa.Integer(), nullable=False),
    sa.Column('qty_change', sa.Integer(), nullable=False),
    sa.Column('qty_after', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['adjustment_id'], ['stock_adjustments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['batch_id'], ['medicine_batches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['medicine_id'], ['medicines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stock_adjustment_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stock_adjustment_items_adjustment_id'), ['adjustment_id'], unique=False)

    op.create_table('compliance_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('record_type', sa.Enum('schedule_h', 'schedule_h1', 'narcotic', 'rx_log'), nullable=False),
    sa.Column('sale_id', sa.Integer(), nullable=True),
    sa.Column('medicine_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('doctor_id', sa.Integer(), nullable=True),
    sa.Column('prescription_id', sa.Integer(), nullable=True),
    sa.Column('quantity_dispensed', sa.Integer(), nullable=True),
    sa.Column('dispensed_date', sa.DateTime(), nullable=True),
    sa.Column('dispensed_by', sa.Integer(), nullable=True),
    sa.Column('batch_number', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['dispensed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['medicine_id'], ['medicines.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['prescription_id'], ['prescriptions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('compliance_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_compliance_records_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_compliance_records_dispensed_date'), ['dispensed_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_compliance_records_record_type'), ['record_type'], unique=False)

    op.create_table('loyalty_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('sale_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.Enum('earn', 'redeem', 'expire', 'adjust'), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('balance', sa.Integer(), nullable=False),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('loyalty_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_loyalty_transactions_patient_id'), ['patient_id'], unique=False)

    op.create_table('purchase_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purchase_id', sa.Integer(), nullable=False),
    sa.Column('medicine_id', sa.Integer(), nullable=False),
    sa.Column('batch_number', sa.String(length=50), nullable=False),
    sa.Column('mfg_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('free_quantity', sa.Integer(), nullable=True),
    sa.Column('purchase_rate', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('mrp', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('discount_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('gst_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('cgst_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('sgst_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('igst_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['medicine_id'], ['medicines.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['purchase_id'], ['purchases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('purchase_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchase_items_purchase_id'), ['purchase_id'], unique=False)

    op.create_table('purchase_returns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('return_number', sa.String(length=25), nullable=False),
    sa.Column('original_purchase_id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('return_date', sa.Date(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('status', sa.Enum('pending', 'sent', 'credited'), nullable=True),
    sa.Column('credit_note_number', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['original_purchase_id'], ['purchases.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('purchase_returns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchase_returns_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_returns_return_number'), ['return_number'], unique=True)

    op.create_table('sale_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sale_id', sa.Integer(), nullable=False),
    sa.Column('medicine_id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('mrp', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('selling_rate', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('discount_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('gst_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('cgst_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('sgst_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('igst_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['medicine_batches.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['medicine_id'], ['medicines.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sale_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sale_items_sale_id'), ['sale_id'], unique=False)

    op.create_table('sales_returns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('return_number', sa.String(length=25), nullable=False),
    sa.Column('original_sale_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('return_date', sa.DateTime(), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('total_refund', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('refund_mode', sa.Enum('cash', 'card', 'upi', 'credit_note'), nullable=True),
    sa.Column('processed_by', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'processed'), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['original_sale_id'], ['sales.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['processed_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sales_returns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sales_returns_return_number'), ['return_number'], unique=True)

    op.create_table('purchase_return_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('return_id', sa.Integer(), nullable=False),
    sa.Column('medicine_id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('rate', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['medicine_batches.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['medicine_id'], ['medicines.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['return_id'], ['purchase_returns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sales_return_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('return_id', sa.Integer(), nullable=False),
    sa.Column('sale_item_id', sa.Integer(), nullable=False),
    sa.Column('medicine_id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('refund_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['medicine_batches.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['medicine_id'], ['medicines.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['return_id'], ['sales_returns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sale_item_id'], ['sale_items.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sales_return_items')
    op.drop_table('purchase_return_items')
    with op.batch_alter_table('sales_returns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sales_returns_return_number'))

    op.drop_table('sales_returns')
    with op.batch_alter_table('sale_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sale_items_sale_id'))

    op.drop_table('sale_items')
    with op.batch_alter_table('purchase_returns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_returns_return_number'))
        batch_op.drop_index(batch_op.f('ix_purchase_returns_business_id'))

    op.drop_table('purchase_returns')
    with op.batch_alter_table('purchase_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_items_purchase_id'))

    op.drop_table('purchase_items')
    with op.batch_alter_table('loyalty_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_loyalty_transactions_patient_id'))

    op.drop_table('loyalty_transactions')
    with op.batch_alter_table('compliance_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_compliance_records_record_type'))
        batch_op.drop_index(batch_op.f('ix_compliance_records_dispensed_date'))
        batch_op.drop_index(batch_op.f('ix_compliance_records_business_id'))

    op.drop_table('compliance_records')
    with op.batch_alter_table('stock_adjustment_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_adjustment_items_adjustment_id'))

    op.drop_table('stock_adjustment_items')
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sales_patient_id'))
        batch_op.drop_index(batch_op.f('ix_sales_invoice_number'))
        batch_op.drop_index(batch_op.f('ix_sales_invoice_date'))
        batch_op.drop_index(batch_op.f('ix_sales_business_id'))
        batch_op.drop_index(batch_op.f('ix_sales_branch_id'))

    op.drop_table('sales')
    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchases_supplier_id'))
        batch_op.drop_index(batch_op.f('ix_purchases_business_id'))
        batch_op.drop_index(batch_op.f('ix_purchases_branch_id'))
        batch_op.drop_index(batch_op.f('ix_purchases_bill_number'))

    op.drop_table('purchases')
    with op.batch_alter_table('purchase_order_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_order_items_po_id'))

    op.drop_table('purchase_order_items')
    with op.batch_alter_table('prescription_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prescription_items_prescription_id'))

    op.drop_table('prescription_items')
    with op.batch_alter_table('journal_entry_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_journal_entry_lines_entry_id'))

    op.drop_table('journal_entry_lines')
    with op.batch_alter_table('stock_adjustments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_adjustments_business_id'))
        batch_op.drop_index(batch_op.f('ix_stock_adjustments_branch_id'))

    op.drop_table('stock_adjustments')
    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_orders_supplier_id'))
        batch_op.drop_index(batch_op.f('ix_purchase_orders_po_number'))
        batch_op.drop_index(batch_op.f('ix_purchase_orders_business_id'))
        batch_op.drop_index(batch_op.f('ix_purchase_orders_branch_id'))

    op.drop_table('purchase_orders')
    with op.batch_alter_table('prescriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prescriptions_prescription_code'))
        batch_op.drop_index(batch_op.f('ix_prescriptions_patient_id'))
        batch_op.drop_index(batch_op.f('ix_prescriptions_business_id'))

    op.drop_table('prescriptions')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_is_read'))
        batch_op.drop_index(batch_op.f('ix_notifications_created_at'))
        batch_op.drop_index(batch_op.f('ix_notifications_business_id'))

    op.drop_table('notifications')
    with op.batch_alter_table('medicine_batches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_medicine_batches_medicine_id'))
        batch_op.drop_index(batch_op.f('ix_medicine_batches_branch_id'))

    op.drop_table('medicine_batches')
    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_journal_entries_entry_date'))
        batch_op.drop_index(batch_op.f('ix_journal_entries_business_id'))

    op.drop_table('journal_entries')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_module'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('medicines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_medicines_name'))
        batch_op.drop_index(batch_op.f('ix_medicines_medicine_code'))
        batch_op.drop_index(batch_op.f('ix_medicines_generic_name'))
        batch_op.drop_index(batch_op.f('ix_medicines_business_id'))
        batch_op.drop_index(batch_op.f('ix_medicines_barcode'))

    op.drop_table('medicines')
    with op.batch_alter_table('gst_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gst_transactions_transaction_type'))
        batch_op.drop_index(batch_op.f('ix_gst_transactions_transaction_date'))
        batch_op.drop_index(batch_op.f('ix_gst_transactions_period'))
        batch_op.drop_index(batch_op.f('ix_gst_transactions_fy'))
        batch_op.drop_index(batch_op.f('ix_gst_transactions_business_id'))

    op.drop_table('gst_transactions')
    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_suppliers_supplier_code'))
        batch_op.drop_index(batch_op.f('ix_suppliers_name'))
        batch_op.drop_index(batch_op.f('ix_suppliers_business_id'))

    op.drop_table('suppliers')
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patients_phone'))
        batch_op.drop_index(batch_op.f('ix_patients_patient_code'))
        batch_op.drop_index(batch_op.f('ix_patients_business_id'))
        batch_op.drop_index(batch_op.f('ix_patients_abha_id'))

    op.drop_table('patients')
    with op.batch_alter_table('medicine_categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_medicine_categories_business_id'))

    op.drop_table('medicine_categories')
    op.drop_table('loyalty_programs')
    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_doctors_doctor_code'))
        batch_op.drop_index(batch_op.f('ix_doctors_business_id'))

    op.drop_table('doctors')
    with op.batch_alter_table('chart_of_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chart_of_accounts_business_id'))

    op.drop_table('chart_of_accounts')
    op.drop_table('branches')
    with op.batch_alter_table('sequences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sequences_key'))

    op.drop_table('sequences')
    with op.batch_alter_table('drug_interactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_drug_interactions_drug_b_generic'))
        batch_op.drop_index(batch_op.f('ix_drug_interactions_drug_a_generic'))

    op.drop_table('drug_interactions')
    op.drop_table('businesses')
    # ### end Alembic commands ###
